name: my-project
build-path: .build
libs-path: .libs

# bins:
    # aapt2: bin/aapt2
    # javac: bin/javac
    # kotlinc: bin/kotlinc
    # d8: bin/d8
    # apksigner: bin/apksigner

android:
    sdk-api-version: 34
    sdk-min-api-version: 21

    version-code: 1
    version-name: "1"

    build-type: debug
    view-binding: true

    # sdk-path: env(ANDROID_SDK)
    manifest-path: AndroidManifest.xml
    # assets-path: src/assets
    # jni-path: src/jniLibs
    java-path: src/java
    res-path: src/res

    keystore-path: myproject.keystore
    keystore-alias: myproject
    keystore-store-pass: 87654321
    keystore-key-pass: 87654321
    
    java-version: 17

#dependencies:
    #- androidx.constraintlayout:constraintlayout:2.1.0
    #- com.google.android.material:material:1.12.0
    #- androidx.appcompat:appcompat:1.6.1
